spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mtl_parent?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml  #在mtl-dao子工程的resources中创建 mappers目录
  type-aliases-package: com.qfedu.mtl.beans       # 在mtl-bean子工程创建com.qfedu.mtl.beans 包
server:
  port: 8090
